-- ============================================================
-- RENTIX — Supabase schema (run in SQL Editor)
-- Platform Rental Gadget · "Sewa Aman, Pakai Nyaman"
-- ------------------------------------------------------------
-- Tables: profiles, products, rentals, reviews, promos
-- Auth   : Supabase Auth (auth.users) + profiles (1:1)
-- Security: Row Level Security on every table
-- ============================================================

-- ---------- extensions ----------
create extension if not exists "pgcrypto";

-- ============================================================
-- 1. PROFILES  (extends auth.users, holds E-KYC status)
-- ============================================================
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  phone       text,
  role        text not null default 'renter',     -- renter | lender | both
  is_student  boolean not null default false,     -- unlocks Promo Mahasiswa
  kyc_status  text not null default 'unverified',  -- unverified | pending | verified
  rating      numeric(2,1) default 5.0,
  created_at  timestamptz not null default now()
);

-- create a profile row automatically when a user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'phone', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 2. PRODUCTS
-- ============================================================
create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  owner_id     uuid references public.profiles(id) on delete set null,
  cat          text not null,
  name         text not null,
  img          text,
  price        integer not null,        -- per day (Rp)
  price_week   integer,
  price_month  integer,
  rating       numeric(2,1) default 5.0,
  reviews      integer default 0,
  owner_name   text,
  owner_verified boolean default false,
  badges       text[] default '{}',
  description  text,
  specs        jsonb default '{}',
  available    boolean default true,
  stock        integer default 1,
  is_premium   boolean default false,   -- Premium Vendor Listing (revenue stream)
  city         text default 'Surabaya',
  created_at   timestamptz not null default now()
);

create index if not exists products_cat_idx on public.products(cat);
create index if not exists products_premium_idx on public.products(is_premium);

-- ============================================================
-- 3. RENTALS  (transactions / escrow)
-- ============================================================
create table if not exists public.rentals (
  id           bigint generated by default as identity primary key,
  renter_id    uuid references public.profiles(id) on delete set null,
  product_id   bigint references public.products(id) on delete set null,
  product_name text,
  start_date   date,
  end_date     date,
  qty          integer not null default 1,
  days         integer not null default 1,
  subtotal     integer not null default 0,
  insurance    integer not null default 0,   -- Insurance Margin (5%)
  total        integer not null default 0,
  status       text not null default 'menunggu', -- menunggu | escrow | berjalan | selesai | batal
  created_at   timestamptz not null default now()
);

create index if not exists rentals_renter_idx on public.rentals(renter_id);

-- ============================================================
-- 4. REVIEWS  (two-way: renter<->owner / product)
-- ============================================================
create table if not exists public.reviews (
  id           bigint generated by default as identity primary key,
  author_id    uuid references public.profiles(id) on delete set null,
  product_id   bigint references public.products(id) on delete cascade,
  rental_id    bigint references public.rentals(id) on delete set null,
  direction    text not null default 'to_owner', -- to_owner | to_renter
  rating       integer not null check (rating between 1 and 5),
  text         text,
  author_name  text,
  created_at   timestamptz not null default now()
);

create index if not exists reviews_product_idx on public.reviews(product_id);

-- ============================================================
-- 5. PROMOS  (Promo Mahasiswa / B2B Kampus)
-- ============================================================
create table if not exists public.promos (
  id          bigint generated by default as identity primary key,
  code        text unique not null,
  title       text not null,
  description text,
  discount    integer not null default 0,   -- percent
  audience    text not null default 'all',   -- all | student | campus
  active      boolean not null default true
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.rentals  enable row level security;
alter table public.reviews  enable row level security;
alter table public.promos   enable row level security;

-- profiles: anyone can read, you can only write your own
drop policy if exists "profiles read"   on public.profiles;
drop policy if exists "profiles upsert" on public.profiles;
drop policy if exists "profiles update" on public.profiles;
create policy "profiles read"   on public.profiles for select using (true);
create policy "profiles upsert" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles update" on public.profiles for update using (auth.uid() = id);

-- products: public read; owner can insert/update/delete own
drop policy if exists "products read"   on public.products;
drop policy if exists "products insert" on public.products;
drop policy if exists "products update" on public.products;
drop policy if exists "products delete" on public.products;
create policy "products read"   on public.products for select using (true);
create policy "products insert" on public.products for insert with check (auth.uid() = owner_id or owner_id is null);
create policy "products update" on public.products for update using (auth.uid() = owner_id);
create policy "products delete" on public.products for delete using (auth.uid() = owner_id);

-- rentals: a user sees & creates their own rentals
drop policy if exists "rentals read"   on public.rentals;
drop policy if exists "rentals insert" on public.rentals;
drop policy if exists "rentals update" on public.rentals;
create policy "rentals read"   on public.rentals for select using (auth.uid() = renter_id);
create policy "rentals insert" on public.rentals for insert with check (auth.uid() = renter_id);
create policy "rentals update" on public.rentals for update using (auth.uid() = renter_id);

-- reviews: public read; authenticated users post their own
drop policy if exists "reviews read"   on public.reviews;
drop policy if exists "reviews insert" on public.reviews;
create policy "reviews read"   on public.reviews for select using (true);
create policy "reviews insert" on public.reviews for insert with check (auth.uid() = author_id);

-- promos: public read
drop policy if exists "promos read" on public.promos;
create policy "promos read" on public.promos for select using (active);

-- ============================================================
-- SEED DATA
-- ============================================================

-- Products (mirrors the original static catalogue) ----------
insert into public.products
  (id, cat, name, img, price, price_week, price_month, rating, reviews, owner_name, owner_verified, badges, description, specs, available, stock, is_premium)
values
  (1,'camera','Sony Alpha A7 III Mirrorless','/products/camera-1.jpg',350000,2000000,7000000,4.9,128,'Budi Santoso',true,'{protected,popular}',
   'Kamera mirrorless full-frame dengan sensor 24.2MP BSI CMOS. Eye-tracking AF, video 4K, stabilisasi in-body. Cocok untuk fotografi profesional dan content creation.',
   '{"Sensor":"24.2MP Full-Frame BSI CMOS","ISO":"100-51200","Video":"4K 30fps / 1080p 120fps","Baterai":"~710 shots","Bobot":"650g"}', true, 2, true),
  (2,'laptop','MacBook Pro M3 Pro 14"','/products/laptop-1.jpg',200000,1200000,4000000,4.8,96,'Rini Wahyu',true,'{protected,popular}',
   'MacBook Pro bertenaga chip M3 Pro untuk editing video, rendering 3D, dan coding. RAM 18GB, SSD 512GB.',
   '{"Chip":"Apple M3 Pro","RAM":"18GB Unified","Storage":"512GB SSD","Display":"14.2\" Liquid Retina XDR","Baterai":"~18 jam"}', true, 1, true),
  (3,'projector','Epson EB-X51 Projector Full HD','/products/projector-1.jpg',150000,800000,2500000,4.7,54,'Event Pro ID',true,'{protected}',
   'Proyektor bisnis 3800 lumens untuk presentasi, seminar, dan screening. HDMI, VGA, USB. Layar hingga 300 inci.',
   '{"Brightness":"3800 Lumens","Resolusi":"XGA 1024x768","Throw":"1.04-1.77 rasio","Konektivitas":"HDMI, VGA, USB","Bobot":"2.5kg"}', true, 3, false),
  (4,'ht','Motorola DP1400 HT Set (4 unit)','/products/ht-1.jpg',80000,450000,1500000,4.6,37,'Rizky Event Supply',true,'{protected,popular}',
   'Set 4 unit Handy Talky Motorola DP1400 Digital. Jangkauan hingga 5km. Ideal untuk koordinasi kepanitiaan dan event outdoor.',
   '{"Jangkauan":"5km (open area)","Channel":"16 channel","Baterai":"12 jam","Frekuensi":"UHF 403-527 MHz","Unit":"4 unit/set"}', true, 4, false),
  (5,'drone','DJI Air 3 Drone 4K','/products/drone-1.jpg',400000,2400000,8500000,4.9,73,'AerialShot Studio',true,'{protected,popular,new}',
   'Drone DJI Air 3 dengan kamera dual 4K/60fps dan obstacle avoidance omni-directional. Terbang hingga 46 menit.',
   '{"Kamera":"Dual 4K/60fps","Terbang":"46 menit","Range":"20km","Stabilizer":"3-axis gimbal","Berat":"720g"}', true, 1, true),
  (6,'stabilizer','DJI RS 3 Gimbal Stabilizer','/products/gimbal-1.jpg',120000,680000,2200000,4.7,45,'Cinematech Rental',true,'{protected}',
   'Gimbal 3-axis ringan untuk kamera mirrorless dan DSLR hingga 3kg. ActiveTrack 3.0.',
   '{"Payload":"3kg max","Axis":"3-axis","Baterai":"12 jam","Konektivitas":"Bluetooth 5.0","Bobot":"1.3kg"}', true, 2, false),
  (7,'audio','Shure SM7dB Mic Podcast Set','/products/audio-1.jpg',90000,520000,1700000,4.8,29,'SoundLab Surabaya',true,'{protected,new}',
   'Set mikrofon dinamis Shure SM7dB all-in-one untuk podcast, dubbing, dan live streaming. Broadcast-quality.',
   '{"Tipe":"Dynamic Cardioid","Preamp":"+28dB built-in","Koneksi":"XLR","Respons":"50Hz-20kHz","Paket":"Mic + Stand + Kabel"}', true, 3, false),
  (8,'laptop','ASUS ROG Strix G16 RTX 4070','/products/laptop-2.jpg',175000,1000000,3500000,4.6,61,'GameGear Rental',false,'{popular}',
   'Laptop gaming & rendering Intel Core i9 + RTX 4070 8GB. RAM 32GB DDR5. Ideal untuk rendering 3D dan desain grafis berat.',
   '{"CPU":"Intel Core i9-14900HX","GPU":"RTX 4070 8GB","RAM":"32GB DDR5","Storage":"1TB NVMe","Display":"16\" QHD 240Hz"}', true, 2, false),
  (9,'camera','Canon EOS R6 Mark II','/products/camera-2.jpg',330000,1900000,6500000,4.8,87,'FotoPro Studio',true,'{protected,popular}',
   'Kamera mirrorless full-frame 24.2MP dengan autofokus Dual Pixel CMOS AF II dan video 4K 60fps. Ideal untuk wedding, event, dan videografi.',
   '{"Sensor":"24.2MP Full-Frame CMOS","ISO":"100-102400","Video":"4K 60fps","AF":"Dual Pixel CMOS AF II","Bobot":"588g"}', true, 2, true),
  (10,'camera','Fujifilm X-T5 + 18-55mm','/products/camera-3.jpg',280000,1600000,5500000,4.7,64,'Lensa Kita',true,'{protected}',
   'Kamera mirrorless APS-C 40MP dengan simulasi film khas Fujifilm. Cocok untuk street photography dan content creator.',
   '{"Sensor":"40.2MP APS-C X-Trans","ISO":"125-12800","Video":"6.2K 30fps","Stabilisasi":"IBIS 7 stop","Bobot":"557g"}', true, 3, false),
  (11,'camera','GoPro HERO12 Black','/products/camera-1.jpg',95000,520000,1800000,4.6,112,'ActionCam ID',true,'{protected,popular}',
   'Action camera tahan air 5.3K dengan HyperSmooth 6.0. Cocok untuk vlog perjalanan, olahraga air, dan dokumentasi outdoor.',
   '{"Video":"5.3K 60fps","Stabilisasi":"HyperSmooth 6.0","TahanAir":"10m tanpa case","Baterai":"Enduro","Bobot":"154g"}', true, 5, false),
  (12,'laptop','Dell XPS 15 OLED i7','/products/laptop-3.jpg',185000,1050000,3600000,4.7,53,'TechRent Surabaya',true,'{protected}',
   'Laptop premium layar OLED 3.5K untuk desain dan editing. Intel Core i7, RAM 16GB, RTX 4050.',
   '{"CPU":"Intel Core i7-13700H","GPU":"RTX 4050 6GB","RAM":"16GB DDR5","Storage":"512GB SSD","Display":"15.6\" 3.5K OLED"}', true, 2, false),
  (13,'laptop','Lenovo Legion 5 Ryzen 7','/products/laptop-1.jpg',160000,920000,3200000,4.5,48,'GameGear Rental',false,'{}',
   'Laptop gaming bertenaga AMD Ryzen 7 + RTX 4060. Layar 165Hz, cocok untuk gaming dan rendering ringan.',
   '{"CPU":"AMD Ryzen 7 7840HS","GPU":"RTX 4060 8GB","RAM":"16GB DDR5","Storage":"1TB SSD","Display":"15.6\" 165Hz"}', true, 3, false),
  (14,'projector','BenQ TH685 Gaming Projector','/products/projector-2.jpg',135000,750000,2400000,4.6,41,'Layar Lebar Rental',true,'{protected}',
   'Proyektor Full HD 3500 lumens dengan input lag rendah, cocok untuk nobar, gaming, dan presentasi.',
   '{"Brightness":"3500 Lumens","Resolusi":"1080p Full HD","InputLag":"8.3ms","Konektivitas":"HDMI x2, USB","Bobot":"2.8kg"}', true, 4, false),
  (15,'projector','Epson EB-FH52 Full HD','/products/projector-3.jpg',170000,950000,3000000,4.7,33,'Event Pro ID',true,'{protected,popular}',
   'Proyektor bisnis 4000 lumens Full HD untuk seminar besar dan acara kampus. Konektivitas lengkap.',
   '{"Brightness":"4000 Lumens","Resolusi":"1080p Full HD","Lampu":"12000 jam","Konektivitas":"HDMI, VGA, USB, LAN","Bobot":"3.1kg"}', true, 2, false),
  (16,'audio','Rode Wireless GO II (Dual)','/products/audio-2.jpg',85000,480000,1600000,4.8,58,'SoundLab Surabaya',true,'{protected,popular}',
   'Sistem mikrofon wireless dual-channel untuk wawancara, vlog, dan dokumentasi event. Jangkauan hingga 200m.',
   '{"Channel":"Dual TX + 1 RX","Jangkauan":"200m","Baterai":"7 jam","Rekaman":"Internal 40 jam","Berat":"32g/unit"}', true, 4, false),
  (17,'audio','Zoom H6 Audio Recorder','/products/audio-3.jpg',75000,420000,1400000,4.6,27,'AudioWorks',true,'{protected}',
   'Perekam audio portabel 6-track dengan kapsul mikrofon yang bisa diganti. Standar produksi film & podcast.',
   '{"Track":"6 track simultan","Input":"4 XLR/TRS","Sampling":"24-bit/96kHz","Layar":"LCD warna","Berat":"280g"}', true, 3, false),
  (18,'drone','DJI Mini 4 Pro','/products/drone-2.jpg',280000,1600000,5800000,4.9,69,'AerialShot Studio',true,'{protected,popular,new}',
   'Drone ringan di bawah 249g dengan kamera 4K HDR dan deteksi rintangan segala arah. Tanpa perlu registrasi rumit.',
   '{"Kamera":"4K/60fps HDR","Berat":"<249g","Terbang":"34 menit","Sensor":"Omnidirectional","Transmisi":"O4 20km"}', true, 2, true),
  (19,'stabilizer','Zhiyun Crane M3','/products/gimbal-2.jpg',95000,540000,1850000,4.5,31,'Cinematech Rental',true,'{protected}',
   'Gimbal ringkas untuk kamera mirrorless, action cam, dan smartphone. Lampu fill built-in.',
   '{"Payload":"2kg max","Axis":"3-axis","Baterai":"7.5 jam","FillLight":"Built-in","Bobot":"700g"}', true, 3, false),
  (20,'ht','Baofeng UV-82 HT Set (6 unit)','/products/ht-2.jpg',70000,390000,1300000,4.4,52,'Rizky Event Supply',true,'{protected,popular}',
   'Set 6 unit Handy Talky dual-band untuk koordinasi panitia event besar. Ekonomis dan andal.',
   '{"Jangkauan":"4km (open area)","Channel":"128 channel","Baterai":"2800mAh","Frekuensi":"VHF/UHF dual-band","Unit":"6 unit/set"}', true, 6, false),
  (21,'camera','Sony ZV-E10 Vlog Kit','/products/camera-2.jpg',160000,900000,3100000,4.7,76,'VlogGear ID',true,'{protected,popular}',
   'Kamera APS-C khusus konten kreator dengan layar flip dan mic directional. Ringan untuk vlog harian.',
   '{"Sensor":"24.2MP APS-C","Video":"4K 24fps","Layar":"Flip-out","Mic":"3-capsule directional","Bobot":"343g"}', true, 4, false),
  (22,'camera','Nikon Z6 II Full-Frame','/products/camera-3.jpg',300000,1750000,6000000,4.8,54,'FotoPro Studio',true,'{protected}',
   'Mirrorless full-frame 24.5MP dual processor untuk foto dan video profesional.',
   '{"Sensor":"24.5MP Full-Frame","ISO":"100-51200","Video":"4K 60fps","Slot":"Dual card","Bobot":"705g"}', true, 2, true),
  (23,'camera','Canon G7X Mark III','/products/camera-1.jpg',140000,800000,2700000,4.6,91,'PocketCam',true,'{protected,popular}',
   'Kamera saku premium untuk vlog dan travel. Live streaming langsung ke YouTube.',
   '{"Sensor":"20.1MP 1-inch","Video":"4K 30fps","Zoom":"4.2x optical","Layar":"Flip touchscreen","Bobot":"304g"}', true, 5, false),
  (24,'camera','Sony A7 IV Body','/products/camera-2.jpg',420000,2500000,8800000,4.9,38,'Lensa Kita',true,'{protected,popular,new}',
   'Hybrid full-frame 33MP untuk fotografer dan videografer serius. 4K 60fps oversampling.',
   '{"Sensor":"33MP Full-Frame","ISO":"100-51200","Video":"4K 60fps","AF":"759 titik","Bobot":"658g"}', true, 1, true),
  (25,'camera','Insta360 X4 360 Cam','/products/camera-3.jpg',130000,720000,2500000,4.7,63,'ActionCam ID',true,'{protected,new}',
   'Kamera 360 derajat 8K untuk konten imersif dan reframe kreatif pasca-rekam.',
   '{"Video":"8K 360","TahanAir":"10m","Baterai":"135 menit","Stabilisasi":"FlowState","Bobot":"203g"}', true, 4, false),
  (26,'laptop','MacBook Air M3 13"','/products/laptop-2.jpg',150000,850000,2900000,4.8,82,'TechRent Surabaya',true,'{protected,popular}',
   'Laptop tipis ringan chip M3 untuk mobilitas, desain, dan coding. Baterai seharian.',
   '{"Chip":"Apple M3","RAM":"16GB","Storage":"512GB SSD","Display":"13.6 inci Liquid Retina","Baterai":"18 jam"}', true, 3, true),
  (27,'laptop','HP Spectre x360 14','/products/laptop-3.jpg',170000,980000,3400000,4.6,44,'TechRent Surabaya',true,'{protected}',
   'Laptop 2-in-1 layar OLED sentuh untuk presentasi dan desain. Stylus included.',
   '{"CPU":"Intel Core Ultra 7","RAM":"16GB","Storage":"1TB SSD","Display":"14 inci 2.8K OLED Touch","Berat":"1.4kg"}', true, 2, false),
  (28,'laptop','ASUS Zenbook 14 OLED','/products/laptop-1.jpg',145000,820000,2800000,4.5,57,'GameGear Rental',false,'{popular}',
   'Ultrabook OLED ringan untuk mahasiswa dan pekerja kreatif. Harga bersahabat.',
   '{"CPU":"Ryzen 7 7730U","RAM":"16GB","Storage":"512GB SSD","Display":"14 inci 2.8K OLED","Berat":"1.39kg"}', true, 4, false),
  (29,'laptop','MacBook Pro M3 Max 16"','/products/laptop-2.jpg',350000,2100000,7500000,4.9,29,'TechRent Surabaya',true,'{protected,popular}',
   'Powerhouse untuk editing 8K, rendering 3D, dan machine learning. RAM 36GB.',
   '{"Chip":"Apple M3 Max","RAM":"36GB","Storage":"1TB SSD","Display":"16.2 inci XDR","Baterai":"22 jam"}', true, 1, true),
  (30,'projector','Anker Nebula Capsule 3','/products/projector-1.jpg',90000,500000,1700000,4.5,48,'Layar Lebar Rental',true,'{protected}',
   'Proyektor portabel seukuran kaleng dengan Android TV. Cocok untuk nobar santai.',
   '{"Brightness":"200 ANSI Lumens","Resolusi":"1080p","OS":"Android TV","Baterai":"2.5 jam","Bobot":"950g"}', true, 5, false),
  (31,'projector','Epson EB-2247U WUXGA','/products/projector-2.jpg',195000,1100000,3700000,4.7,26,'Event Pro ID',true,'{protected}',
   'Proyektor 4200 lumens WUXGA untuk auditorium dan seminar besar.',
   '{"Brightness":"4200 Lumens","Resolusi":"WUXGA 1920x1200","Konektivitas":"HDMI, VGA, LAN, WiFi","Lampu":"10000 jam","Bobot":"4.1kg"}', true, 2, false),
  (32,'projector','ViewSonic M2e Portable','/products/projector-3.jpg',110000,620000,2100000,4.4,35,'Layar Lebar Rental',true,'{protected}',
   'Proyektor LED portabel Full HD dengan speaker Harman Kardon.',
   '{"Brightness":"1000 LED Lumens","Resolusi":"1080p","Audio":"Harman Kardon","Konektivitas":"HDMI, USB-C","Bobot":"1.3kg"}', true, 3, false),
  (33,'audio','Shure SM58 Mic Vokal','/products/audio-1.jpg',45000,250000,850000,4.7,73,'SoundLab Surabaya',true,'{protected,popular}',
   'Mikrofon dinamis legendaris untuk vokal panggung dan acara. Tahan banting.',
   '{"Tipe":"Dynamic Cardioid","Respons":"50Hz-15kHz","Koneksi":"XLR","Paket":"Mic + klip + pouch","Berat":"298g"}', true, 8, false),
  (34,'audio','Yamaha MG10XU Mixer','/products/audio-2.jpg',120000,680000,2300000,4.6,31,'AudioWorks',true,'{protected}',
   'Mixer audio 10 channel dengan efek SPX dan USB interface. Untuk band dan event.',
   '{"Channel":"10 input","Efek":"SPX built-in","USB":"24-bit/192kHz","Phantom":"+48V","Berat":"2.1kg"}', true, 3, false),
  (35,'audio','JBL EON715 Speaker Aktif','/products/audio-3.jpg',150000,850000,2900000,4.8,42,'SoundLab Surabaya',true,'{protected,popular}',
   'Speaker aktif 15 inci 1300W untuk acara outdoor dan indoor. Bluetooth dan DSP.',
   '{"Daya":"1300W","Driver":"15 inci","Bluetooth":"Ya","DSP":"Built-in","Berat":"15.4kg"}', true, 4, false),
  (36,'audio','Rode NT1 5th Gen Mic','/products/audio-1.jpg',80000,450000,1550000,4.7,28,'AudioWorks',true,'{protected,new}',
   'Mikrofon kondenser studio dual-output (XLR + USB) untuk rekaman vokal dan podcast.',
   '{"Tipe":"Condenser Cardioid","Output":"XLR + USB-C","Respons":"20Hz-20kHz","SPL":"142dB","Paket":"Mic + shock mount"}', true, 4, false),
  (37,'drone','DJI Mavic 3 Pro','/products/drone-3.jpg',520000,3100000,11000000,4.9,47,'AerialShot Studio',true,'{protected,popular,new}',
   'Drone flagship kamera Hasselblad triple-lens untuk produksi sinematik profesional.',
   '{"Kamera":"Hasselblad 4/3 CMOS","Video":"5.1K 50fps","Terbang":"43 menit","Sensor":"Omnidirectional","Transmisi":"O3+ 15km"}', true, 1, true),
  (38,'drone','DJI Avata 2 FPV','/products/drone-1.jpg',300000,1700000,6000000,4.7,39,'AerialShot Studio',true,'{protected,new}',
   'Drone FPV imersif untuk shot dinamis. Termasuk goggles dan motion controller.',
   '{"Kamera":"4K 60fps","FOV":"155 derajat","Terbang":"23 menit","Berat":"377g","Paket":"+ Goggles 3"}', true, 2, false),
  (39,'drone','DJI Air 2S','/products/drone-2.jpg',230000,1300000,4600000,4.6,55,'SkyView Rental',true,'{protected}',
   'Drone serbaguna sensor 1 inci 5.4K. Pilihan favorit kreator travel.',
   '{"Kamera":"20MP 1-inch","Video":"5.4K 30fps","Terbang":"31 menit","Range":"12km","Berat":"595g"}', true, 2, false),
  (40,'stabilizer','DJI RS 4 Pro','/products/gimbal-3.jpg',160000,900000,3100000,4.8,33,'Cinematech Rental',true,'{protected,popular}',
   'Gimbal profesional payload 4.5kg untuk kamera cinema. Auto-axis lock.',
   '{"Payload":"4.5kg max","Axis":"3-axis","Baterai":"29 jam","Layar":"1.8 inci OLED","Bobot":"1.23kg"}', true, 2, true),
  (41,'stabilizer','DJI Osmo Mobile 6','/products/gimbal-1.jpg',55000,300000,1050000,4.5,88,'Cinematech Rental',true,'{protected,popular}',
   'Gimbal smartphone 3-axis dengan extension rod dan ActiveTrack 6.0.',
   '{"Payload":"Smartphone","Axis":"3-axis","Baterai":"6.4 jam","Fitur":"ActiveTrack 6.0","Bobot":"309g"}', true, 6, false),
  (42,'stabilizer','Hohem iSteady MT2 Kit','/products/gimbal-2.jpg',70000,400000,1400000,4.4,24,'CreatorKit',true,'{protected}',
   'Gimbal multifungsi untuk kamera, action cam, dan HP. Termasuk AI tracker.',
   '{"Payload":"1.2kg","Axis":"3-axis","Baterai":"19 jam","Fitur":"AI tracker + fill light","Bobot":"625g"}', true, 3, false),
  (43,'ht','Motorola XiR P3688 (4 unit)','/products/ht-3.jpg',110000,620000,2100000,4.6,29,'Rizky Event Supply',true,'{protected}',
   'Set 4 HT digital tahan air IP55 untuk operasional event dan keamanan.',
   '{"Jangkauan":"6km","Channel":"16 channel","Baterai":"16 jam","Proteksi":"IP55","Unit":"4 unit/set"}', true, 4, false),
  (44,'ht','Icom IC-V86 (2 unit)','/products/ht-1.jpg',60000,340000,1150000,4.5,33,'Rizky Event Supply',true,'{protected}',
   'Sepasang HT VHF 7W bertenaga besar untuk jangkauan luas di area terbuka.',
   '{"Jangkauan":"8km","Daya":"7W","Baterai":"3100mAh","Frekuensi":"VHF","Unit":"2 unit/set"}', true, 5, false),
  (45,'ht','Baofeng UV-5R (4 unit)','/products/ht-2.jpg',45000,250000,880000,4.3,61,'Rizky Event Supply',true,'{protected,popular}',
   'Set 4 HT dual-band ekonomis untuk panitia dan kegiatan komunitas.',
   '{"Jangkauan":"3km","Channel":"128 channel","Baterai":"1800mAh","Frekuensi":"VHF/UHF","Unit":"4 unit/set"}', true, 8, false),
  (46,'camera','DJI Pocket 3 Creator Combo','/products/camera-1.jpg',150000,850000,2900000,4.8,57,'PocketCam',true,'{protected,popular,new}',
   'Kamera gimbal saku 4K untuk vlog stabil. Combo dengan mic dan handle.',
   '{"Sensor":"1-inch CMOS","Video":"4K 120fps","Layar":"2 inci rotatable","Gimbal":"3-axis","Bobot":"179g"}', true, 4, true),
  (47,'laptop','Microsoft Surface Laptop 5','/products/laptop-3.jpg',155000,880000,3000000,4.5,36,'TechRent Surabaya',true,'{protected}',
   'Laptop premium tipis untuk produktivitas dan presentasi. Layar sentuh 3:2.',
   '{"CPU":"Intel Core i7-1255U","RAM":"16GB","Storage":"512GB SSD","Display":"13.5 inci Touch 3:2","Berat":"1.27kg"}', true, 2, false),
  (48,'audio','Sennheiser e835 Mic (2 unit)','/products/audio-2.jpg',60000,340000,1150000,4.6,22,'SoundLab Surabaya',true,'{protected}',
   'Sepasang mikrofon vokal dinamis untuk duet dan MC acara.',
   '{"Tipe":"Dynamic Cardioid","Respons":"40Hz-16kHz","Koneksi":"XLR","Unit":"2 unit/set","Berat":"330g/unit"}', true, 4, false),
  (49,'projector','XGIMI Horizon Ultra 4K','/products/projector-1.jpg',260000,1500000,5200000,4.8,19,'Layar Lebar Rental',true,'{protected,new}',
   'Proyektor 4K Dolby Vision dengan Google TV untuk home cinema dan screening premium.',
   '{"Brightness":"2300 ISO Lumens","Resolusi":"4K UHD","HDR":"Dolby Vision","OS":"Google TV","Audio":"Harman Kardon"}', true, 2, true),
  (50,'drone','DJI Neo Mini Drone','/products/drone-3.jpg',90000,500000,1750000,4.5,44,'SkyView Rental',true,'{protected,popular}',
   'Drone mungil 135g untuk pemula dan selfie udara. Lepas landas dari telapak tangan.',
   '{"Kamera":"4K","Berat":"135g","Terbang":"18 menit","Fitur":"Palm takeoff","Mode":"QuickShots"}', true, 5, false)
on conflict (id) do nothing;

-- keep the identity sequence ahead of the seeded ids
select setval(pg_get_serial_sequence('public.products','id'), (select max(id) from public.products));

-- Reviews (seed product reviews, direction = to_owner) ------
insert into public.reviews (product_id, direction, rating, text, author_name) values
  (1,'to_owner',5,'Proses sewa sangat mudah, barang datang tepat waktu dan kondisinya sempurna. Kamera Sony-nya keren banget!','Alya R.'),
  (3,'to_owner',5,'Pertama kali pakai Rentix dan langsung puas. Proyektornya untuk seminar lancar jaya, garansi asuransinya bikin tenang.','Dimas K.'),
  (2,'to_owner',4,'MacBook Pro yang disewa bersih dan kencang banget. Proses verifikasi KTP cepat. Recommended!','Farah N.'),
  (4,'to_owner',5,'HT buat event kampus kami sukses. 4 unit semuanya berfungsi baik. Harga terjangkau dibanding beli.','Bima S.'),
  (6,'to_owner',5,'Gimbal DJI RS3 memuaskan banget. Konten kami makin pro. Pasti balik lagi ke Rentix!','Sari M.'),
  (5,'to_owner',4,'Drone Air 3 kualitasnya luar biasa. Operator gampang diajak komunikasi.','Yogi P.')
on conflict do nothing;

-- Promos (Promo Mahasiswa / B2B Kampus) ---------------------
insert into public.promos (code, title, description, discount, audience) values
  ('MAHASISWA20','Diskon Mahasiswa 20%','Khusus mahasiswa terverifikasi (KTM). Berlaku untuk semua kategori, sepanjang semester.',20,'student'),
  ('EVENTKAMPUS','Paket Event Kampus','Sewa alat untuk BEM/Hima/UKM. Harga khusus paket HT + proyektor + sound.',15,'campus'),
  ('TUGASAKHIR','Promo Tugas Akhir','Sewa kamera & laptop untuk dokumentasi dan pengerjaan tugas akhir.',10,'student'),
  ('WELCOME10','Selamat Datang','Diskon untuk transaksi pertama semua pengguna baru Rentix.',10,'all')
on conflict (code) do nothing;
