-- ============================================================
-- RENTIX — Supabase schema (run in SQL Editor)
-- Platform Rental Gadget · "Sewa Aman, Pakai Nyaman"
-- ------------------------------------------------------------
-- Tables: profiles, products, rentals, reviews, promos
-- Auth   : Supabase Auth (auth.users) + profiles (1:1)
-- Security: Row Level Security on every table
-- ============================================================

-- ---------- extensions ----------
create extension if not exists "pgcrypto";

-- ============================================================
-- 1. PROFILES  (extends auth.users, holds E-KYC status)
-- ============================================================
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  full_name   text,
  phone       text,
  role        text not null default 'renter',     -- renter | lender | both
  is_student  boolean not null default false,     -- unlocks Promo Mahasiswa
  kyc_status  text not null default 'unverified',  -- unverified | pending | verified
  rating      numeric(2,1) default 5.0,
  created_at  timestamptz not null default now()
);

-- create a profile row automatically when a user signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'phone', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- 2. PRODUCTS
-- ============================================================
create table if not exists public.products (
  id           bigint generated by default as identity primary key,
  owner_id     uuid references public.profiles(id) on delete set null,
  cat          text not null,
  name         text not null,
  img          text,
  price        integer not null,        -- per day (Rp)
  price_week   integer,
  price_month  integer,
  rating       numeric(2,1) default 5.0,
  reviews      integer default 0,
  owner_name   text,
  owner_verified boolean default false,
  badges       text[] default '{}',
  description  text,
  specs        jsonb default '{}',
  available    boolean default true,
  stock        integer default 1,
  is_premium   boolean default false,   -- Premium Vendor Listing (revenue stream)
  city         text default 'Surabaya',
  created_at   timestamptz not null default now()
);

create index if not exists products_cat_idx on public.products(cat);
create index if not exists products_premium_idx on public.products(is_premium);

-- ============================================================
-- 3. RENTALS  (transactions / escrow)
-- ============================================================
create table if not exists public.rentals (
  id           bigint generated by default as identity primary key,
  renter_id    uuid references public.profiles(id) on delete set null,
  product_id   bigint references public.products(id) on delete set null,
  product_name text,
  start_date   date,
  end_date     date,
  qty          integer not null default 1,
  days         integer not null default 1,
  subtotal     integer not null default 0,
  insurance    integer not null default 0,   -- Insurance Margin (5%)
  total        integer not null default 0,
  status       text not null default 'menunggu', -- menunggu | escrow | berjalan | selesai | batal
  created_at   timestamptz not null default now()
);

create index if not exists rentals_renter_idx on public.rentals(renter_id);

-- ============================================================
-- 4. REVIEWS  (two-way: renter<->owner / product)
-- ============================================================
create table if not exists public.reviews (
  id           bigint generated by default as identity primary key,
  author_id    uuid references public.profiles(id) on delete set null,
  product_id   bigint references public.products(id) on delete cascade,
  rental_id    bigint references public.rentals(id) on delete set null,
  direction    text not null default 'to_owner', -- to_owner | to_renter
  rating       integer not null check (rating between 1 and 5),
  text         text,
  author_name  text,
  created_at   timestamptz not null default now()
);

create index if not exists reviews_product_idx on public.reviews(product_id);

-- ============================================================
-- 5. PROMOS  (Promo Mahasiswa / B2B Kampus)
-- ============================================================
create table if not exists public.promos (
  id          bigint generated by default as identity primary key,
  code        text unique not null,
  title       text not null,
  description text,
  discount    integer not null default 0,   -- percent
  audience    text not null default 'all',   -- all | student | campus
  active      boolean not null default true
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.rentals  enable row level security;
alter table public.reviews  enable row level security;
alter table public.promos   enable row level security;

-- profiles: anyone can read, you can only write your own
drop policy if exists "profiles read"   on public.profiles;
drop policy if exists "profiles upsert" on public.profiles;
drop policy if exists "profiles update" on public.profiles;
create policy "profiles read"   on public.profiles for select using (true);
create policy "profiles upsert" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles update" on public.profiles for update using (auth.uid() = id);

-- products: public read; owner can insert/update/delete own
drop policy if exists "products read"   on public.products;
drop policy if exists "products insert" on public.products;
drop policy if exists "products update" on public.products;
drop policy if exists "products delete" on public.products;
create policy "products read"   on public.products for select using (true);
create policy "products insert" on public.products for insert with check (auth.uid() = owner_id or owner_id is null);
create policy "products update" on public.products for update using (auth.uid() = owner_id);
create policy "products delete" on public.products for delete using (auth.uid() = owner_id);

-- rentals: a user sees & creates their own rentals
drop policy if exists "rentals read"   on public.rentals;
drop policy if exists "rentals insert" on public.rentals;
drop policy if exists "rentals update" on public.rentals;
create policy "rentals read"   on public.rentals for select using (auth.uid() = renter_id);
create policy "rentals insert" on public.rentals for insert with check (auth.uid() = renter_id);
create policy "rentals update" on public.rentals for update using (auth.uid() = renter_id);

-- reviews: public read; authenticated users post their own
drop policy if exists "reviews read"   on public.reviews;
drop policy if exists "reviews insert" on public.reviews;
create policy "reviews read"   on public.reviews for select using (true);
create policy "reviews insert" on public.reviews for insert with check (auth.uid() = author_id);

-- promos: public read
drop policy if exists "promos read" on public.promos;
create policy "promos read" on public.promos for select using (active);

-- ============================================================
-- SEED DATA
-- ============================================================

-- Products (mirrors the original static catalogue) ----------
insert into public.products
  (id, cat, name, img, price, price_week, price_month, rating, reviews, owner_name, owner_verified, badges, description, specs, available, stock, is_premium)
values
  (1,'camera','Sony Alpha A7 III Mirrorless','/product_camera.png',350000,2000000,7000000,4.9,128,'Budi Santoso',true,'{protected,popular}',
   'Kamera mirrorless full-frame dengan sensor 24.2MP BSI CMOS. Eye-tracking AF, video 4K, stabilisasi in-body. Cocok untuk fotografi profesional dan content creation.',
   '{"Sensor":"24.2MP Full-Frame BSI CMOS","ISO":"100-51200","Video":"4K 30fps / 1080p 120fps","Baterai":"~710 shots","Bobot":"650g"}', true, 2, true),
  (2,'laptop','MacBook Pro M3 Pro 14"','/product_laptop.png',200000,1200000,4000000,4.8,96,'Rini Wahyu',true,'{protected,popular}',
   'MacBook Pro bertenaga chip M3 Pro untuk editing video, rendering 3D, dan coding. RAM 18GB, SSD 512GB.',
   '{"Chip":"Apple M3 Pro","RAM":"18GB Unified","Storage":"512GB SSD","Display":"14.2\" Liquid Retina XDR","Baterai":"~18 jam"}', true, 1, true),
  (3,'projector','Epson EB-X51 Projector Full HD','/product_projector.png',150000,800000,2500000,4.7,54,'Event Pro ID',true,'{protected}',
   'Proyektor bisnis 3800 lumens untuk presentasi, seminar, dan screening. HDMI, VGA, USB. Layar hingga 300 inci.',
   '{"Brightness":"3800 Lumens","Resolusi":"XGA 1024x768","Throw":"1.04-1.77 rasio","Konektivitas":"HDMI, VGA, USB","Bobot":"2.5kg"}', true, 3, false),
  (4,'ht','Motorola DP1400 HT Set (4 unit)','/product_ht.png',80000,450000,1500000,4.6,37,'Rizky Event Supply',true,'{protected,popular}',
   'Set 4 unit Handy Talky Motorola DP1400 Digital. Jangkauan hingga 5km. Ideal untuk koordinasi kepanitiaan dan event outdoor.',
   '{"Jangkauan":"5km (open area)","Channel":"16 channel","Baterai":"12 jam","Frekuensi":"UHF 403-527 MHz","Unit":"4 unit/set"}', true, 4, false),
  (5,'drone','DJI Air 3 Drone 4K','/product_drone.png',400000,2400000,8500000,4.9,73,'AerialShot Studio',true,'{protected,popular,new}',
   'Drone DJI Air 3 dengan kamera dual 4K/60fps dan obstacle avoidance omni-directional. Terbang hingga 46 menit.',
   '{"Kamera":"Dual 4K/60fps","Terbang":"46 menit","Range":"20km","Stabilizer":"3-axis gimbal","Berat":"720g"}', true, 1, true),
  (6,'stabilizer','DJI RS 3 Gimbal Stabilizer','/product_gimbal.png',120000,680000,2200000,4.7,45,'Cinematech Rental',true,'{protected}',
   'Gimbal 3-axis ringan untuk kamera mirrorless dan DSLR hingga 3kg. ActiveTrack 3.0.',
   '{"Payload":"3kg max","Axis":"3-axis","Baterai":"12 jam","Konektivitas":"Bluetooth 5.0","Bobot":"1.3kg"}', true, 2, false),
  (7,'audio','Shure SM7dB Mic Podcast Set','/product_microphone.png',90000,520000,1700000,4.8,29,'SoundLab Surabaya',true,'{protected,new}',
   'Set mikrofon dinamis Shure SM7dB all-in-one untuk podcast, dubbing, dan live streaming. Broadcast-quality.',
   '{"Tipe":"Dynamic Cardioid","Preamp":"+28dB built-in","Koneksi":"XLR","Respons":"50Hz-20kHz","Paket":"Mic + Stand + Kabel"}', true, 3, false),
  (8,'laptop','ASUS ROG Strix G16 RTX 4070','/product_laptop.png',175000,1000000,3500000,4.6,61,'GameGear Rental',false,'{popular}',
   'Laptop gaming & rendering Intel Core i9 + RTX 4070 8GB. RAM 32GB DDR5. Ideal untuk rendering 3D dan desain grafis berat.',
   '{"CPU":"Intel Core i9-14900HX","GPU":"RTX 4070 8GB","RAM":"32GB DDR5","Storage":"1TB NVMe","Display":"16\" QHD 240Hz"}', true, 2, false)
on conflict (id) do nothing;

-- keep the identity sequence ahead of the seeded ids
select setval(pg_get_serial_sequence('public.products','id'), (select max(id) from public.products));

-- Reviews (seed product reviews, direction = to_owner) ------
insert into public.reviews (product_id, direction, rating, text, author_name) values
  (1,'to_owner',5,'Proses sewa sangat mudah, barang datang tepat waktu dan kondisinya sempurna. Kamera Sony-nya keren banget!','Alya R.'),
  (3,'to_owner',5,'Pertama kali pakai Rentix dan langsung puas. Proyektornya untuk seminar lancar jaya, garansi asuransinya bikin tenang.','Dimas K.'),
  (2,'to_owner',4,'MacBook Pro yang disewa bersih dan kencang banget. Proses verifikasi KTP cepat. Recommended!','Farah N.'),
  (4,'to_owner',5,'HT buat event kampus kami sukses. 4 unit semuanya berfungsi baik. Harga terjangkau dibanding beli.','Bima S.'),
  (6,'to_owner',5,'Gimbal DJI RS3 memuaskan banget. Konten kami makin pro. Pasti balik lagi ke Rentix!','Sari M.'),
  (5,'to_owner',4,'Drone Air 3 kualitasnya luar biasa. Operator gampang diajak komunikasi.','Yogi P.')
on conflict do nothing;

-- Promos (Promo Mahasiswa / B2B Kampus) ---------------------
insert into public.promos (code, title, description, discount, audience) values
  ('MAHASISWA20','Diskon Mahasiswa 20%','Khusus mahasiswa terverifikasi (KTM). Berlaku untuk semua kategori, sepanjang semester.',20,'student'),
  ('EVENTKAMPUS','Paket Event Kampus','Sewa alat untuk BEM/Hima/UKM. Harga khusus paket HT + proyektor + sound.',15,'campus'),
  ('TUGASAKHIR','Promo Tugas Akhir','Sewa kamera & laptop untuk dokumentasi dan pengerjaan tugas akhir.',10,'student'),
  ('WELCOME10','Selamat Datang','Diskon untuk transaksi pertama semua pengguna baru Rentix.',10,'all')
on conflict (code) do nothing;
